### ISSUE TITLE
Field Bug

### ISSUE THREAD

**Issue by jamesjpk123** [ursa-majors/co-ment#227]
![ow5f1yikvd](https://user-images.githubusercontent.com/18013689/31524291-c65396e6-af75-11e7-96af-e8ae942dd890.gif)

I'm trying to edit my profile, but whenever I type into fields, it deletes everything I type instantly.

**Comment by rifkegribenes** [comment]
Hi @jamesjpk123 I just tried to reproduce this bug and was not able to. Can you let me know what browser you are using? Are you still having the issue if you log out and log in again or reload the app?

**Comment by jamesjpk123** [comment]
Yesterday, I logged out and in again, and the bug persisted. Once I get to my computer I used yesterday, I can tell you my browser info.

**Comment by rifkegribenes** [comment]
OK thanks. Please also try reloading the app (navigating to Home and refreshing your browser), and let me know if you're still seeing the same issue.

**Comment by jamesjpk123** [comment]
Ok, I tried again on Chrome Mobile v61.0.3163.73 and had the same issue. Reopening the page has it still retain the bug. I will get back to you on the chrome version I used when the bug happened originally.

**Comment by jamesjpk123** [comment]
Ok the original browser I used was Chrome 61.0.3163.100 on PC.

**Comment by michaelgee22** [comment]
I seem to be having the same problem on most major vendor browsers.

**Comment by belcurv** [comment]
@jamesjpk123 and @michaelgee22 - I'm sorry, but I am unable to reproduce the bug either.
Is there anything logged to your browser(s) console?

**Comment by michaelgee22** [comment]
![pic](https://user-images.githubusercontent.com/17189731/31672316-3accd0ac-b32a-11e7-83c5-80786deee174.PNG)

This seems to be the reoccurring error I am getting

**Comment by belcurv** [comment]
Thanks @michaelgee22

**Comment by belcurv** [comment]
@jamesjpk123  and @michaelgee22 --
Would you mind testing again? Please log off and back on before testing.

**Comment by michaelgee22** [comment]
Yep! Everything seems to be working great now

**Comment by belcurv** [comment]
Awesome. Thanks again for being my test pilot on this. I have to do a little cleanup and what-not, and may break the app again before I'm done ;) Just FYI in case you see the issue return.

I'll wait for @jamesjpk123 to confirm working before closing the issue.

**Comment by jamesjpk123** [comment]
Working perfectly for me now! Thanks!
