### ISSUE TITLE
Cannot edit/delete message after the character limit

### ISSUE THREAD

**Issue by ykmsd** [ursa-majors/co-ment#258]
Hello! I just found a bug - once you write more than the character limit, you cannot type anything and cannot delete it too.

I was writing a long message for my mentorship request and I noticed that I couldn't do anything once I wrote more than 620 characters. I needed to refresh the page and had to rewrite it. Would be great at least I can delete them.

**Comment by belcurv** [comment]
Hi @ykmsd - I confirm the bug. Thanks for raising this issue. Will investigate.

**Comment by rifkegribenes** [comment]
fixed! @ykmsd thanks for flagging :)

**Comment by ykmsd** [comment]
Yay thanks for fixing! I love the product, keep up with the great work 👍
