### ISSUE TITLE
Bug Report - Profile Tabs - Languages

### ISSUE THREAD

**Issue by C-F-4** [ursa-majors/co-ment#279]
I encountered a bug while going through the website on [this page](https://co-ment.glitch.me/profile)

I already have languages and skills set in my profile data. Now when I navigate to my Profile by clicking on my profile picture at the top right. By default, Skills tab is selected. Now when I click on Languages, it will result in any empty tab panel.

Browser Details - Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)

![co-ment-profile-bug000](https://user-images.githubusercontent.com/9998053/54082218-086b7380-4338-11e9-9b50-dae8c3819584.PNG)
![co-ment-profile-bug001](https://user-images.githubusercontent.com/9998053/54082219-09040a00-4338-11e9-82dd-f5d937f436c0.PNG)
![co-ment-profile-bug002](https://user-images.githubusercontent.com/9998053/54082220-09040a00-4338-11e9-9612-6491ff7f28dd.PNG)
![co-ment-profile-bug003](https://user-images.githubusercontent.com/9998053/54082221-099ca080-4338-11e9-9a76-3667615f6822.PNG)

I also verified the response in the Network Tab. The /profile/:id API seems to be returning correct response.

```
"languages": [
    "English",
    "Hindi"
  ]
```

**Comment by belcurv** [comment]
Thanks for the detailed bug report. I confirm your experience. What's worse, in FF, after clicking on 'Languages" and clicking back on "Skills", now the skills tab is empty. :thinking:

**Comment by C-F-4** [comment]
> Thanks for the detailed bug report. I confirm your experience. What's worse, in FF, after clicking on 'Languages" and clicking back on "Skills", now the skills tab is empty. 🤔

@belcurv Yes I encountered that, but I think that could be just due to second panel switch breakage. From that point onward, it stops marking the tabs as active on clicking on them.

**Comment by genestd** [comment]
@C-F-4 - There's kind of a weird selector for setting the active tab in state, and it was coming back null.  I've fixed this particular error and deployed, but your issue made me realize that the app could use some major refactoring, so thanks again for the report and for giving us a spark to work on it again.
